/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ican_ytx_com_demuxer_MediaDemuxer */

#ifndef _Included_ican_ytx_com_demuxer_MediaDemuxer
#define _Included_ican_ytx_com_demuxer_MediaDemuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ican_ytx_com_demuxer_MediaDemuxer
 * Method:    demuxer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ican_ytx_com_demuxer_MediaDemuxer_demuxer
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
