/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ican_ytx_com_remuxer_MediaRemuxer */

#ifndef _Included_ican_ytx_com_remuxer_MediaRemuxer
#define _Included_ican_ytx_com_remuxer_MediaRemuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ican_ytx_com_remuxer_MediaRemuxer
 * Method:    remuxer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ican_ytx_com_remuxer_MediaRemuxer_remuxer
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
